version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${PORT:-8080}:${PORT:-8080}"
    volumes:
      - api_data:/app/data

volumes:
  api_data:
